org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
	mod_id=verdance
	minecraft_version=1.21.7
	yarn_mappings=1.21.7+build.8
	loader_version=0.16.14
	loom_version=1.11-SNAPSHOT

# Mod Properties
	mod_version = 1.2.0
	maven_group = com.teamabode
	archives_base_name = verdance

# Dependencies
	fabric_version=0.129.0+1.21.7
	sketch_version=1.21.1-1.2.1
	biolith_version=3.3.2

# Compatibility Dependencies
	farmers_delight_version=1.21.8-3.2.5